// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from effect_player.djinni

#import <Foundation/Foundation.h>


__attribute__((__visibility__("default"))) @interface BNBDebugInterface : NSObject

- (void)setAutotestConfig:(nonnull NSString *)config;

@end
