// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, BNBGestureType)
{
    BNBGestureTypeNoGesture,
    BNBGestureTypeLike,
    BNBGestureTypeOk,
    BNBGestureTypePalm,
    BNBGestureTypeRock,
    BNBGestureTypeVictory,
};
