// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, BNBTriggerStatusType)
{
    BNBTriggerStatusTypeOpened,
    BNBTriggerStatusTypeClosed,
    BNBTriggerStatusTypeExists,
    BNBTriggerStatusTypeDoesntExist,
};
