// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>
@class BNBImage;


/** Class, which provide camera composer algorithms adjust interface. */
__attribute__((__visibility__("default"))) @interface BNBCameraComposer : NSObject

/**
 * Pass empty path to reset background image.
 * Supported extensions: jpg, jpeg, png, mp4, gif
 */
- (void)setBackgroundImage:(nonnull NSString *)path;

- (nullable BNBImage *)getBackgroundImage;

- (void)enableBlur:(BOOL)enable;

- (void)setBlurRadius:(int32_t)radius;

- (void)setBgTransparencyFactor:(float)factor;

- (void)setRotation:(float)degrees;

- (void)setScale:(float)x
               y:(float)y;

- (void)setContentMode:(int32_t)mode;

- (void)setBackgroundColor:(float)r
                         g:(float)g
                         b:(float)b
                         a:(float)a;

@end
