// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>
@class BNBImage;


__attribute__((__visibility__("default"))) @interface BNBWeightedLut : NSObject

- (void)setWeight:(float)value;

- (float)getWeight;

- (void)load:(nonnull NSString *)fileName;

/**@return upcast to base type */
- (nullable BNBImage *)asImage;

@end
