/// \file
/// \addtogroup Utils
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from utils.djinni

#pragma once

#include <bnb/utils/defs.hpp>
#include <cstdint>

namespace bnb { namespace interfaces {

/**
 * Only android interface.
 * The interface required for the correct closing of java image,
 * after pointers of the image planes have been freed on the cpp side.
 */
class BNB_EXPORT image_releaser {
public:
    virtual ~image_releaser() {}

    /**
     * Increments the reference count for an interface pointer to a object.
     * @param amount number of add ref.
     * MUST be called before release().
     */
    virtual void add_ref(int32_t amount) = 0;

    /**
     * Decrements the reference count for an interface on a COM object.
     * After the last ref is deleted, the java image will be closed(released).
     * MUST be called from the deleters of bnb::color_plane.
     */
    virtual void release() = 0;
};

} }  // namespace bnb::interfaces
/// @}

